### ISSUE TITLE
Python pyproject.toml does not generate the protobufs

### ISSUE THREAD

**Issue by cyberkaida** [cyberkaida/reverse-engineering-assistant#51]
```
(env) D:\github\reverse-engineering-assistant\reverse-engineering-assistant>reva-chat
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\-\.local\bin\reva-chat.exe\__main__.py", line 4, in <module>
  File "C:\Users\-\pipx\venvs\reverse-engineering-assistant\Lib\site-packages\reverse_engineering_assistant\chat_client.py", line 22, in <module>
    from .protocol.RevaChat_pb2_grpc import RevaChatServiceStub
ModuleNotFoundError: No module named 'reverse_engineering_assistant.protocol'
```

https://github.com/cyberkaida/reverse-engineering-assistant/blob/280bfe8fecaf5a11927e3175b5c9e5b492624072/reverse-engineering-assistant/reverse_engineering_assistant/chat_client.py#L19-L23

**Comment by cyberkaida** [comment]
Is there a better way than this hack to make the protobuf generated code import?

**Comment by cyberkaida** [comment]
Probably did not run the makefile
https://github.com/cyberkaida/reverse-engineering-assistant/blob/280bfe8fecaf5a11927e3175b5c9e5b492624072/Makefile#L21

Unfortunately the `pyproject.toml` does not trigger the protobuf build like the gradle does in Java.

**Comment by cyberkaida** [comment]
Stale.
